name: "units-test-edge"
on:
  # works for mannual, in case of github agent updated.
  # we can run mannually to see if it can be fixed by update version of
  # - kubectl
  # - k8s cluster provider's
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # folder exists should not blocking process
  test_local_cluster_withEdgeCase_folder_exists:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: start from local
      run: |
        mkdir -p /tmp/kubeconfig
        export CLUSTER_PROVIDER=kind
        export CLUSTER_CONFIG=false
        ./main.sh up
    - name: test as kepler action behavior
      run: |
        mkdir -p /tmp/kubeconfig
        cp .kube/config /tmp/kubeconfig
        export PROMETHEUS_ENABLE=true
        export TEKTON_ENABLE=true
        export KUBECONFIG_ROOT_DIR=/tmp/kubeconfig
        ./main.sh config
    - name: verify cluster
      run: |
        ./verify.sh verify_cluster

  test_local_cluster_withEdgeCase_file_exists:
  # file exists should not blocking process
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: start from local
      run: |
        echo 1 > /tmp/kubeconfig
        export CLUSTER_PROVIDER=kind
        export CLUSTER_CONFIG=false
        ./main.sh up
    - name: test as kepler action behavior
      run: |
        mkdir -p /tmp/kubeconfig
        cp .kube/config /tmp/kubeconfig
        export PROMETHEUS_ENABLE=true
        export TEKTON_ENABLE=true
        export KUBECONFIG_ROOT_DIR=/tmp/kubeconfig
        ./main.sh config
    - name: verify cluster
      run: |
        ./verify.sh verify_cluster